jar 'org.kill-bill.billing:killbill-api', '0.9.5'
jar 'org.kill-bill.billing.plugin:killbill-plugin-api-notification', '0.7.2'
jar 'org.kill-bill.billing.plugin:killbill-plugin-api-payment', '0.7.2'
jar 'org.kill-bill.billing.plugin:killbill-plugin-api-currency', '0.7.2'
jar 'org.kill-bill.billing:killbill-util:tests', '0.11.2'
jar 'javax.servlet:javax.servlet-api', '3.0.1'
