jar 'com.ning.billing:killbill-api', '0.7.8'
jar 'com.ning.billing.plugin:killbill-plugin-api-notification', '0.6.2'
jar 'com.ning.billing.plugin:killbill-plugin-api-payment', '0.6.2'
jar 'com.ning.billing.plugin:killbill-plugin-api-currency', '0.6.2'
jar 'com.ning.billing:killbill-util:tests', '0.7.1'
jar 'javax.servlet:javax.servlet-api', '3.0.1'
