jar 'com.ning.billing:killbill-api', '0.7.1'
jar 'com.ning.billing.plugin:killbill-plugin-api-notification', '0.5.0'
jar 'com.ning.billing.plugin:killbill-plugin-api-payment', '0.5.0'
jar 'com.ning.billing:killbill-util:tests', '0.6.17'
jar 'javax.servlet:javax.servlet-api', '3.0.1'
